=== 15831944/PanelColorAlbum/AlbumPanelColorTiles/Model/Base/Panels.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Panels">
    <xs:complexType>
      <xs:sequence maxOccurs ="unbounded">
        <xs:element name="Panel">
          <xs:complexType>
            <xs:sequence maxOccurs="1" minOccurs="1">
              <xs:element name="gab">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="length" type="xs:double" />
                    <xs:element name="height" type="xs:double" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="windows" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence maxOccurs="unbounded">
                    <xs:element name="window">
                      <xs:complexType>
                        <xs:sequence maxOccurs ="1">
                          <xs:element name="width" type="xs:double" />
                          <xs:element name="height" type="xs:double" />
                          <xs:element name="posi">
                            <xs:complexType>
                              <xs:sequence maxOccurs="1">
                                <xs:element name="X" type="xs:double" />
                                <xs:element name="Y" type="xs:double" />
                                <xs:element name="Z" type="xs:double" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="mark" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== 15831944/PanelColorAlbum/AlbumPanelColorTiles/Model/Base/Panels - копия.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--<Panels xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Panels.xsd">-->
<Panels>
	<Panel mark="3НСг 72.29.32-5"> 
		<gab>
			<length> 7188.0 </length>
			<height> 2808.0 </height> 
		</gab>
		<windows> 
			<window> 
				<width>600.0</width>
				<height>1805.0</height> 
				<posi>
					<X>894.0</X>
					<Y>489.0</Y>
					<Z>0.0</Z>      
				</posi> 
			</window>
			<window>
				<width>1200.0</width>
				<height>1805.0</height>
				<posi>
					<X>1794.0</X>
					<Y>489.0</Y>
					<Z>0.0</Z>
				</posi> 
			</window>
			<window> 
				<width>600.0</width>
				<height>1805.0</height>
				<posi>
					<X>4494.0</X>
					<Y>489.0</Y>
					<Z>0.0</Z>
				</posi>
			</window>
			<window>
				<width>1200.0</width>
				<height>1805.0</height>
				<posi>
					<X>5394.0</X>
					<Y>489.0</Y>
					<Z>0.0</Z>
				</posi>
			</window>
		</windows> 
	</Panel>
	<Panel mark="3НСг 72.29.32-1"> 
		<gab>
			<length>7188.0</length>
			<height>2808.0</height> 
		</gab>
		<windows> 
			<window> 
				<width>1500.0</width>
				<height>1805.0</height>
				<posi>
					<X>894.0</X>
					<Y>489.0</Y>
					<Z>0.0</Z>
				</posi> 
			</window>
			<window>
				<width>1500.0</width>
				<height>1805.0</height>
				<posi>
					<X>4794.0</X>
					<Y>489.0</Y>
					<Z>0.0</Z>
				</posi>
			</window> 
		</windows>
	</Panel>
	<Panel mark="3НСг 72.29.32"> 
		<gab> 
			<length>7188.0</length>
			<height>2808.0</height> 
		</gab>
		<windows> 
			<window> 
				<width>1810.0</width>
				<height>1805.0</height>
				<posi>
					<X>889.0</X>
					<Y>489.0</Y>
					<Z>0.0</Z>
				</posi> 
			</window>
			<window> 
				<width>1800.0</width>        
				<height>1805.0</height>
				<posi>
					<X>4494.0</X>
					<Y>489.0</Y>
					<Z>0.0</Z>
				</posi>        
			</window> 
		</windows> 
	</Panel>
	<Panel mark="3НСг 72.29.32-16"> 
		<gab> 
			<length>7188.0</length>
			<height>2808.0</height>
		</gab>
		<windows> 
			<window> 
				<width>1500.0</width>
				<height>1805.0</height>
				<posi>
					<X>894.0</X>
					<Y>489.0</Y>
					<Z>0.0</Z>
				</posi> 
			</window>
			<window> 
				<width>1500.0</width>
				<height>1805.0</height>
				<posi>
					<X>4494.0</X>
					<Y>489.0</Y>
					<Z>0.0</Z>
				</posi> 
			</window> 
		</windows> 
	</Panel>  
</Panels>

=== 15831944/PanelColorAlbum/AlbumPanelColorTiles/Model/Base/Panels.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Panels xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Panels.xsd">
	<Panel mark = "3НСг 72.29.32-17">
		<gab>
			<length> 7188.0 </length>
			<height> 2788.0 </height>
		</gab>
		<cheeks>  </cheeks>
		<windows> 
			<window> 
				<width> 1500.0 </width>
				<height> 1805.0 </height>
				<posi>
					<X> 1494.0 </X> <Y> 489.0 </Y> <Z> 0.0 </Z>
				</posi> 
			</window>
			<window>
				<width> 1500.0 </width>
				<height> 1805.0 </height>
				<posi>
					<X> 5094.0 </X> <Y> 489.0 </Y> <Z> 0.0 </Z>
				</posi> 
			</window>
		</windows>
		<balcony>  </balcony>
		<undercuts>  </undercuts>
	</Panel>
	<Panel mark = "3НСг 39.29.32-8-1П2">
		<gab>
			<length> 3889.0 </length>
			<height> 2788.0 </height>
		</gab>
		<cheeks>
			<cheek> right </cheek>
		</cheeks>
		<windows>
			<window> 
				<width> 1200.0 </width>
				<height> 1805.0 </height>
				<posi>
					<X> 1195.0 </X> <Y> 489.0 </Y> <Z> 0.0 </Z>
				</posi>
			</window>
			<window>
				<width> 600.0 </width>
				<height> 1805.0 </height>
				<posi>
					<X> 2695.0 </X> <Y> 489.0 </Y> <Z> 0.0 </Z>
				</posi>
			</window>
		</windows> 
		<balcony>  </balcony>
		<undercuts>
			<undercut>
				<width> 1200.0 </width>
				<height> 200.0 </height>
				<posi>
					<X> 1195.0 </X> <Y> 2608.0 </Y> <Z> 0.0 </Z>
				</posi>
			</undercut>
		</undercuts>
	</Panel>
	<Panel mark = "3НСг 39.29.32-8-1Б">
		<gab>
			<length> 3889.0 </length>
			<height> 2788.0 </height>
		</gab>
		<cheeks>
			<cheek> right </cheek>
		</cheeks>
		<windows> 
			<window> 
				<width> 1200.0 </width>
				<height> 1805.0 </height>
				<posi>
					<X> 1195.0 </X> <Y> 489.0 </Y> <Z> 0.0 </Z>
				</posi> 
			</window>
			<window>
				<width> 600.0 </width>
				<height> 1805.0 </height>
				<posi>
					<X> 2695.0 </X> <Y> 489.0 </Y> <Z> 0.0 </Z>
				</posi>
			</window> 
		</windows>
		<balcony>  </balcony>
		<undercuts>  </undercuts>
	</Panel>
	<Panel mark = "3НСг 39.29.32-8-1">
		<gab> 
			<length> 3889.0 </length>
			<height> 2788.0 </height>
		</gab>
		<cheeks>
			<cheek> right </cheek>
		</cheeks>
		<windows> 
			<window> 
				<width> 1200.0 </width>
				<height> 1805.0 </height>
				<posi>
					<X> 1195.0 </X> <Y> 489.0 </Y> <Z> 0.0 </Z>
				</posi> 
			</window>
			<window> 
				<width> 600.0 </width>
				<height> 1805.0 </height>
				<posi>
					<X> 2695.0 </X> <Y> 489.0 </Y> <Z> 0.0 </Z>
				</posi>        
			</window> 
		</windows> 
		<balcony>  </balcony>
		<undercuts>  </undercuts>
	</Panel>
	<Panel mark = "3НСг 39.29.32-2-1Б">
		<gab> 
			<length> 3889.0 </length>
			<height> 2788.0 </height>
		</gab>
		<cheeks>
			<cheek> left </cheek>
		</cheeks>
		<windows> 
			<window> 
				<width> 1200.0 </width>
				<height> 1805.0 </height>
				<posi>
					<X> 894.0 </X> <Y> 489.0 </Y> <Z> 0.0 </Z>
				</posi> 
			</window>
			<window> 
				<width> 600.0 </width>
				<height> 1805.0 </height>
				<posi>
					<X> 2394.0 </X> <Y> 489.0 </Y> <Z> 0.0 </Z>
				</posi> 
			</window> 
		</windows> 
		<balcony>			
			<width>1200.0</width>
			<height> 205.0 </height>
			<posi>
				<X> 894.0 </X> <Y> 0.0 </Y> <Z> 0.0 </Z>
			</posi>
		</balcony>
		<undercuts>  </undercuts>
	</Panel>
</Panels>
